### ISSUE TITLE
Try to keep indentation consistent

### ISSUE THREAD

**Issue by Jbarget** [super4minions/Autocomplete#14]
Hello! :) 

Just reading through your code and would find it a lot easier to read if the indentation is consistent
:)

https://github.com/super4minions/Autocomplete/blob/master/router.js#L2
https://github.com/super4minions/Autocomplete/blob/master/frontend/index2.js
https://github.com/super4minions/Autocomplete/blob/master/frontend/js.js

**Comment by mohanagy** [comment]
Thank you very much for your comment. 
We have fixed it!
